baseURL = "https://blog.bwasd.io"
languageCode = "en-us"
title = "Barry Wasdell"
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]
    [[menu.nav]]
        name = "Barry Wasdell's Blog"
        url = "/"
        weight = -100
    [[menu.nav]]
        name = "Github"
        weight = -80
        url = "https://github.com/bwasd"
    [[menu.nav]]
        name = "Feed"
        weight = -70
        url = "/index.xml"
    [[menu.nav]]
        name = "About"
        weight = -90
        url = "/about"
