baseURL = "https://blog.bwasd.io"
languageCode = "en-us"
title = "Barry Wasdell"
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]
summaryLength = 70
disableHugoGeneratorInject = true

[params]
  AuthorName = "Barry Wasdell"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]

[menu]
    [[menu.nav]]
        name = "Barry's Blog"
        url = "/"
        weight = -100
    [[menu.nav]]
        name = "Feed"
        weight = -70
        url = "/index.xml"
    [[menu.nav]]
        name = "About"
        weight = -90
        url = "/about"
